@startmindmap
skinparam monochrome true
skinparam defaultFontName IPAexGothic
* 悪魔ほむら派閥
** 悪魔ほむらは正しいよ（ほむら肯定派）
*** まどかやさやかもなぎさも蘇って完璧な終幕だよ（ハッピーエンド派）
*** 本当はみんなと仲良くしたいのに関係を断ち切ったほむらは可哀想だよ（使い魔本音派）
*** 初めてほむらが本音を見せたから許してあげようよ（ほむら同情派）
*** まどかの願いはほむらの想いを無視してたよ（ほむらの願い尊重派）
*** 本編からしてこうなる事は自明だったよ（ほむら心情派）
** QBが悪いんだよ（QB絶対悪派）
*** あんな実験をしたから自業自得だよ（QBざまぁ派）
*** あのまま円環されたら後々まどかはQBのものになってたよ（悪魔妥当派）
*** QBに感情が生まれてまた逆襲してくるよ（続編待望派）
*** QBもいたぶられて喜んでるよ（ほむQ派）
** 悪魔ほむらは間違ってるよ（ほむら否定派）
*** 使い魔もいるしまどかは目覚めそうだし不安定な世界すぎるよ（バッドエンド派）
*** ほむら自身が幸せになってないよ（まどか視点派）
*** まどかの願いを否定してるよ（まどかの願い尊重派）;
*** エゴだよそれは（アムロ派）;
*** ほむらは気が狂ってるよ（ほむらヤンデレ派）;
*** 唯一敵対しているさやかに倒して欲しいんだよ（さやほむ派）;
** 悪魔ほむらは可愛いよ（悪魔崇拝派）
*** 全員救ったほむらは悪魔じゃなくて女神だよ（アルティメットほむら派）;
*** 記憶改竄とか凄いよ最強だよ（悪魔万能説派）;
*** 指先でつんつんされたいよ（QBちょっと変われ派）;
*** 悪魔ぶってるほむらちゃん可愛いよ（私って悪魔ね派）;
*** 毎回まどかを抱きしめたい口実を作りたかったんだよ（ほむまど派）;
*** 悪魔になってもまどかの前ではヘタレなんだよ（まどほむ派）;
** 愛よ（愛なら仕方ない派）;
@endmindmap